baseURL: "https://seraphine-arts.com"
defaultContentLanguage: de
languages:
  de:
    title: "Seraphine Arts"
    weight: 1
  en:
    title: "Seraphine Arts"
    weight: 2
markup:
  goldmark:
    renderer: 
      unsafe: true